--- # delius_primarydb.yml

database_global_database: PRENDA
database_taf_service: PRENDA_TAF
database_primary_unique: PRENDA
database_primary_sid: PRENDA
rman_level_0_backup_duration_target: "21:00"
rman_uncompressed_backup: Y
cfo_database_directory: "/u01/app/oracle/admin/{{ database_global_database }}/cfo/shared_files/National/cfo"
delius_users:
  amarke_ro:
  jstanley_ro:
  mwillis_ro:
  pphillips_ro:
  smitchell_ro:
